import React from "react";
import Breadcrumb from "@/components/Breadcrumb";

export default function page() {
	const breadcrumbItems = [
		{ label: "Home", href: "/" },
		{ label: "Blog", href: "/blog" },
		{ label: "Article 3", href: "/blog/article3" },
	];
	return (
		<div className="bg-gray-100 text-gray-800 mt-[100px] container md:w-4/5 w-full my-16">
			<a href="/blog">
				<div className="md:hidden fixed top-[105px] left-[2px] p-2 rounded-[50%] bg-black text-white text-[16px] font-bold w-8 h-8 flex justify-center items-center">
					&lt;-
				</div>
			</a>
			<Breadcrumb items={breadcrumbItems} />
			<header className="bg-blue-600 text-white p-6">
				<h1 className="text-2xl font-bold">
					India Bullish on AI in Healthcare Without Electronic Health Records
				</h1>
			</header>

			<main className="md:p-6 max-w-4xl mx-auto">
				<section className="mb-6">
					<p className="text-lg mb-4">
						With more than 75% of outpatients and more than 60% of inpatients in
						India being treated in private healthcare facilities, why is the
						adoption of EHR a challenge in India?
					</p>
					<p className="text-lg mb-4">
						79-year-old Karan Singh, a lung cancer patient undergoing treatment
						since 11 years, recalls the number of times he had to carry folders
						bulging with photocopies of medical reports, the repeated blood
						tests in different hospitals, and the sleepless nights caused by
						painful side effects of drugs, chemotherapy, and radiation.
					</p>
					<p className="text-lg mb-4">
						Today, even after all these years of treatment, Karan has never
						heard about electronic health records (EHR). HIMSS Health
						Information and Technology Resource Library defines Electronic
						Health Record (EHR) as a longitudinal electronic record of patient
						health information generated by one or more encounters in any care
						delivery setting. This includes patient demographics, progress
						notes, problems, medications, vital signs, past medical history,
						immunisations, laboratory data, and radiology reports.
					</p>
					<p className="text-lg mb-4">
						Imagine the impact of EHR on Karan&apos;s course of treatment if
						systems had flagged early detection of cancer and provided insight
						into the most effective methods of treatment based on data collected
						as electronic health records from a huge number of patients.
					</p>
				</section>

				<section className="mb-6">
					<h2 className="text-xl font-semibold mb-2">
						Kerala’s Success with EHR
					</h2>
					<p className="mb-4">
						While the governments continue to give hope, Kerala is the only
						state in India which has successfully collected and stored
						electronic health records of 2.58 crore people through its ‘eHealth
						project’. The state government initiative allows patients to walk
						into any government hospital without carrying any papers.
					</p>
					<p className="mb-4">
						Sharing insight about Kerala’s eHealth project, Dr. Shabeer Ali,
						Managing Director of HODO, a Trivandrum-based software company that
						develops electronic health records, said, 86 government hospitals in
						the state have implemented the eHealth project, and 2.58 crore
						people have been empanelled in this system. In Kerala, while the
						public sector has taken this initiative to collate health
						information, the private sector is new at adopting such technology.
					</p>
				</section>

				<section className="mb-6">
					<h2 className="text-xl font-semibold mb-2">
						The National Digital Health Blueprint (NDHB)
					</h2>
					<p className="mb-4">
						The National Digital Health Blueprint (NDHB), proposed in 2019,
						plans to establish and manage the health data and infrastructure
						required for its seamless exchange, promoting adoption of open
						standards and developing several digital health systems that span
						from wellness to disease management. Interestingly, the NDHB also
						aims at leveraging information systems already existing in the
						health sector.
					</p>
					<p className="mb-4">
						Fortunately, today, healthcare experts and clinicians in India do
						understand the potential of artificial intelligence and big data.
						However, implementation of standardized electronic health records
						can only be seen in radiology, billing, and registration systems.
					</p>
				</section>

				<section className="mb-6">
					<h2 className="text-xl font-semibold mb-2">
						Challenges and Potential of EHR in India
					</h2>
					<p className="mb-4">
						“Most of the IT systems in leading hospitals are primarily for
						billing and their records and not EHRs in a real sense. The
						administration has to understand the fact that there has to be a
						plan to make EHRs a reality, and without EHRs, we cannot have any
						clinical data for implementing AI or Big Data, as there will be no
						data,” said Prof. Rajendra Pratap Gupta, public policy expert who
						serves on the Digital Health Guidelines group at WHO.
					</p>
					<p className="mb-4">
						With more than 75% of outpatients and more than 60% of inpatients in
						India being treated in private healthcare facilities, the government
						urgently needs to bring these establishments on-board for using EHR.
					</p>
					<p className="mb-4">
						According to Dr. M. W. Ghori, Executive Director at Medical and
						Health Information Management Association, a blockchain
						technology-driven EHR has the potential to transform Indian
						healthcare, placing the patient at the centre of the healthcare
						ecosystem and increasing the security, privacy, and interoperability
						of health data.
					</p>
				</section>

				<section className="mb-6">
					<h2 className="text-xl font-semibold mb-2">
						The Roadmap for EHR Implementation
					</h2>
					<p className="mb-4">
						Currently, the Hospital Information System (HIS) software is used in
						India. Adoption of EHR in hospitals automates and streamlines the
						clinician&apos;s workflow and its adoption can be a means by which
						hospitals tap into improving healthcare delivery by capturing
						structured healthcare information.
					</p>
					<p className="mb-4">
						Only after we have the data can we think of artificial intelligence
						becoming a reality as the power of AI lies in its ability to analyze
						extremely large amounts of data coming in from a spectrum of sources
						– including EHRs, consumer devices, radiology, and sensor data.
					</p>
					<p className="mb-4">
						“If we feed in the data of all public hospitals, we could create a
						robust decision support system (DSS) tool to help newly passed-out
						doctors. This will be a big boost to the accuracy of diagnosis and
						treatment. We could impact clinical outcomes, predict seasonal
						outbreaks and NCDs,” added Prof. Rajendra Pratap Gupta.
					</p>
					<p className="mb-4">
						Wockhardt Group of Hospital&apos;s CHIO, Girish Koppar, believes EHR
						adoption will see the evolution of predictive treatment rather than
						reactive treatment and help in leveraging AI and ML technologies
						which can be life-saving.
					</p>
				</section>

				<section className="mb-6">
					<h2 className="text-xl font-semibold mb-2">
						Current Status and Future Directions
					</h2>
					<p className="mb-4">
						In the latest review report prepared by the Ministry of Electronics
						and Information Technology (MeitY) titled “Adoption of Electronic
						Health Records: A Roadmap for India,” highlighted that government
						hospitals and dispensaries have very little ICT infrastructure with
						only some major public hospitals, such as the All India Institute of
						Medical Sciences (AIIMS) and the Postgraduate Institute of Medical
						Education and Research (PGIMER), having computers and connectivity.
					</p>
					<p className="mb-4">
						Except for a handful of large healthcare organizations in India,
						there has not been a major effort towards EHR implementation.
						Smaller hospitals will find EHR implementation a major cost hurdle,
						feels Swanand Prabhutendolkar, Sr. Vice President - Healthcare Data
						Management at CitiusTech.
					</p>
					<p className="mb-4">
						“Electronic health records were never a technology challenge but an
						adoption challenge which only dissolves when clinicians realize the
						potential of EHR or when there is a mandate either from top
						management or from the government,” said Prashant Singh, Director
						and Chief Information Officer at Max Healthcare.
					</p>
					<p className="mb-4">
						Max Healthcare, which uses the Vista EHR system, is currently
						leveraging speech-to-text technology to capture data for reducing
						medical errors in medicine administration. The hospital is also
						evaluating technologies to make EHR available on the doctors tablet
						or mobile for better patient care and data capturing.
					</p>
				</section>

				<section className="mb-6">
					<h2 className="text-xl font-semibold mb-2">
						Addressing EHR Implementation Challenges
					</h2>
					<p className="mb-4">
						Different hospitals can have varied budgets and approaches to the
						adoption of electronic healthcare records. Now while data can be
						available in many formats, it is important to mandate some standards
						for the data to be analyzable and to achieve interoperability.
					</p>
					<p className="mb-4">
						Deen Sulbigar Ali Ahamed, Group Head of IT, Columbia Asia Group of
						Hospitals, emphasized the need for significant adoption of common
						EHR data standards such as FHIR to ensure seamless transfer of
						patient data between hospitals.
					</p>
					<p className="mb-4">
						“Gaps in EHR data for any given patient (for example, data from a
						particular provider is missing) can significantly reduce the
						credibility of data and practitioners would be unwilling to make
						clinical decisions based on EHR.”
					</p>
					<p className="mb-4">
						There has to be greater emphasis on the quality of the available
						clinical data without errors which is critical to enable widespread
						adoption. The review report prepared by MeitY revealed
						infrastructure creation, policy and regulations, standards, and
						interoperability as challenges.
					</p>
					<p className="mb-4">
						Prashant Singh shared similar concerns, “EHR standards on the ground
						are nowhere. Government of India has not mandated those records as
						of now and it is available as a part of minimum data sets for EHR.”
					</p>
					<p className="mb-4">
						According to him, everyone first has to follow one standard and then
						only we can think of interoperability. “There needs to be a clear
						mandate i.e., capturing at least a minimum data set, otherwise I
						don&apos;t see its probability in the near future.”
					</p>
				</section>

				<section className="mb-6">
					<h2 className="text-xl font-semibold mb-2">
						Scaling EHR Adoption through Incentives
					</h2>
					<p className="mb-4">
						EHR implementation, which is a long-drawn effort, requires
						significant spends on technology, people, and data digitization.
						While a few private hospitals do have some kind of EHR system in
						place, the majority of hospitals are still functioning on
						handwritten reports.
					</p>
					<p className="mb-4">
						This non-adoption of an EHR system is further delaying the
						collection of the required amount of data. One of the measures
						suggested by Prof. Rajendra Pratap Gupta is that the Ministry of
						Health should get a basic ‘functional EHR’ developed, host it on a
						secure cloud (Health Information Exchange), and give it for free to
						clinicians and hospitals.
					</p>
					<p className="mb-4">
						“Smaller hospitals will find EHR implementation a major cost hurdle.
						Government incentivization for technology adoption may be needed to
						help these organizations overcome the cost challenge,” said Swanand
						Prabhutendolkar.
					</p>
					<p className="mb-4">
						The experts believed that well-defined incentives for providers
						could really scale up adoption of EHR and also encourage hospitals
						to share patient data towards common EHR systems.
					</p>
				</section>

				<section className="mb-6">
					<h2 className="text-xl font-semibold mb-2">Realigning the Focus</h2>
					<p className="mb-4">
						Today, everyone is talking about how artificial intelligence could
						revolutionize healthcare delivery, but the reality outlines the
						major gaps in the implementation of electronic medical records. With
						the slow approach towards the adoption of EHR systems for capturing
						data, we are not even at the starting point of using technologies
						like artificial intelligence, let alone big data.
					</p>
					<p className="mb-4">
						I do not believe that Big Data is a notion that hospitals should
						focus on. It would be more prudent to build analytics that can
						quantify clinical quality and help improve care protocols and
						outcomes, stated Swanand Prabhutendolkar.
					</p>
					<p className="mb-4">
						The Meaningful Use incentive programs, which were started by the US
						more than a decade ago, had their initial focus on EHR deployment
						and clinical quality measurement. It is only in the third phase of
						the program that the focus changed to deeper goals like clinical
						decision support, accountable care, and patient engagement.
					</p>
					<p className="mb-4">
						Israel, a small country with a population of just 9 million, is a
						good example to learn the importance of investing in health data.
						Their healthcare system has been paperless for the last 20 years,
						which has helped achieve major insights on adrenal failure,
						hemoglobin levels, and colon cancer. Even though the EHR systems of
						different hospitals are not the same, they are still very well
						connected. Last year, Israel’s cabinet approved a $276 million
						investment in digital health, focusing primarily on commercializing
						and otherwise deriving value from the country’s medical databanks.
					</p>
					<p className="mb-4">
						Citing Israel’s example, Prof. Rajendra Pratap Gupta said, “If we
						give financial incentives, we would just have to spend about Rs 100
						crores to set up a secure Health Information Exchange (HIE). So, for
						a cash-strapped government looking at creating jobs, AI and big data
						in healthcare is a phenomenal opportunity.”
					</p>
					<p className="mb-4">
						Big Data and AI can play an important role in improving healthcare
						outcomes but only once we have some of the foundational data and
						analytics pieces in place. India, which is seeing a drastic rise in
						heart diseases, diabetes, and pulmonary diseases, needs to
						strengthen its healthcare providers with EHR systems to effectively
						study disease patterns and reduce the burden.
					</p>
				</section>
			</main>
		</div>
	);
}
